title: Manyfold
description: Organise your 3d print files
theme: just-the-docs
color_scheme: dark

url: https://manyfold.app

aux_links:
  Source Code: https://github.com/manyfold3d/manyfold

nav_external_links:
  - title: Releases
    url: https://github.com/manyfold3d/manyfold/releases

collections:
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title:output_ext

callouts:
  warning:
    title: Warning
    color: red
