title: Manyfold
description: A self-hosted web app for organising and managing 3d models for printing
theme: just-the-docs

url: https://manyfold.app

aux_links:
  Source Code: https://github.com/manyfold3d/manyfold

nav_external_links:
  - title: Releases
    url: https://github.com/manyfold3d/manyfold/releases

